services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: orcamentos-otaodev
    image: otaodev/orcamentos
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - otao-orcamentos

  nginx:
    image: nginx:latest
    container_name: orcamentos-otaodev-nginx
    ports:
      - 8000:80
      - 445:443
    volumes:
      - ./:/var/www
      - ./.infra/develop/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - otao-orcamentos
    depends_on:
      - app
    
networks:
  otao-orcamentos:
    driver: bridge