name: 🚀 Deploy orcamentos.otao.dev.br
on:
  push:
    branches:
      - main

jobs:
  running_unit_tests:
    name: 🧪 Running application tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy .env
        working-directory: ./
        run: cp .env.example .env && echo APP_ENV=prod >> .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: php-cs-fixer, cs2pr

      - name: Composer Install
        working-directory: ./
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Validate composer.json and composer.lock
        working-directory: ./
        run: composer validate --strict

      - name: PHPUnit Tests
        working-directory: ./
        run: vendor/bin/phpunit --coverage-html=coverage --coverage-clover=coverage/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LC_ALL: "pt_BR.UTF-8"

  build:
    needs: running_unit_tests
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout do repositorio
        uses: actions/checkout@v4

      - name: Copy .env
        working-directory: ./
        run: cp .env.example .env && echo APP_ENV=prod >> .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: php-cs-fixer, cs2pr

      - name: 🔨 Build Project
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Validate composer.json and composer.lock
        working-directory: ./
        run: composer validate --strict

      - name: 📂 Deploy para Hostgator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}