name: 🚀 Deploy orcamentos.otao.dev.br
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout do repositorio
        uses: actions/checkout@v4

      - name: 🔨 Build Project
        run: |
          composer install

      - name: 📂 Deploy para Hostgator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}