name: Validate Pull Requests
on:
  pull_request:
    branches:
      - main

jobs:
  running_unit_tests:
    name: 🧪 Running application tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy .env
        working-directory: ./
        run: |
          cp .env.example .env.testing 
          echo APP_ENV=testing >> .env.testing
          echo DB_DATABASE=database/database.sqlite >> .env.testing

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: php-cs-fixer, cs2pr

      - name: Composer Install
        working-directory: ./
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Validate composer.json and composer.lock
        working-directory: ./
        run: composer validate --strict

      # Crie o arquivo SQLite
      - name: Create SQLite Database
        run: touch database/database.sqlite

      # Execute as migrações para o banco de dados de teste
      - name: Run Migrations
        run: |
          php artisan key:generate --show --env=testing
          php artisan migrate --env=testing

      - name: PHPUnit Tests
        working-directory: ./
        run: vendor/bin/phpunit --coverage-html=coverage --coverage-clover=coverage/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LC_ALL: "pt_BR.UTF-8"