name: Validate Pull Requests
on:
  pull_request:
    branches:
      - main

jobs:
  running_unit_tests:
    name: 🧪 Running application tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy .env
        working-directory: ./
        run: cp .env.example .env.database && echo APP_ENV=testing >> .env.database

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: php-cs-fixer, cs2pr

      - name: Composer Install
        working-directory: ./
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Validate composer.json and composer.lock
        working-directory: ./
        run: composer validate --strict

      # - name: Running Artisan commands
      #   working-directory: ./
      #   run: php artisan key:generate

      - name: PHPUnit Tests
        working-directory: ./
        run: vendor/bin/phpunit --coverage-html=coverage --coverage-clover=coverage/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LC_ALL: "pt_BR.UTF-8"

